media: "src/assets"
public_path: "../../assets"

content:
  - name: "pages"
    label: "Pages"
    type: "collection"
    path: "src/content/pages"
    format: "frontmatter"
    fields:
      - name: "title"
        label: "Page Title"
        type: "string"
      - name: "intro_title"
        label: "Intro Title"
        type: "string"
      - name: "intro_subtitle"
        label: "Intro Subtitle"
        type: "string"
      - name: "intro_text"
        label: "Intro Text"
        type: "text"
      - name: "intro_image"
        label: "Intro Image"
        type: "image"
      - name: "body"
        label: "Body Content (About)"
        type: "rich-text"

  - name: "projects"
    label: "Projects"
    type: "collection"
    path: "src/content/projects"
    format: "frontmatter"
    fields:
      - name: "title"
        label: "Title"
        type: "string"
      - name: "image"
        label: "Image"
        type: "image"
      - name: "link"
        label: "Repo Link"
        type: "string"
      - name: "preview"
        label: "Preview Link"
        type: "string"
      - name: "status"
        label: "Status"
        type: "select"
        options:
          - "Deployed"
          - "On Development"
          - "Contributor"
          - "Archived"
      - name: "description"
        label: "Short Description"
        type: "string"
      - name: "body"
        label: "Full Description"
        type: "rich-text"

  - name: "services"
    label: "Services"
    type: "collection"
    path: "src/content/services"
    format: "frontmatter"
    fields:
      - name: "title"
        label: "Title"
        type: "string"
      - name: "image"
        label: "Image/Icon"
        type: "image"
      - name: "order"
        label: "Order"
        type: "number"
      - name: "body"
        label: "Description"
        type: "rich-text"

  - name: "articles"
    label: "Articles / Approach"
    type: "collection"
    path: "src/content/articles"
    format: "frontmatter"
    fields:
      - name: "title"
        label: "Title"
        type: "string"
      - name: "date"
        label: "Date"
        type: "date"
      - name: "home_display"
        label: "Display on Home"
        type: "select"
        options:
          - "full"
          - "summary"
          - "hidden"
      - name: "body"
        label: "Content"
        type: "rich-text"
